package com.old.silence.content.domain.model.takeout;

import jakarta.persistence.Entity;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

import java.math.BigInteger;
import java.util.List;

import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

/**
 * @author moryzang
 */
@Entity
@Table(name = "pre_category")
public class Category extends AbstractAutoGeneratedIdAuditable<BigInteger> {


    private String name;

    private Long sort;

    @OneToMany(mappedBy = "category")
    private List<Food> foods;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getSort() {
        return sort;
    }

    public void setSort(Long sort) {
        this.sort = sort;
    }

    public List<Food> getFoods() {
        return foods;
    }

    public void setFoods(List<Food> foods) {
        this.foods = foods;
    }
}
