package com.old.silence.content.domain.model.codegen;

import jakarta.persistence.Entity;
import jakarta.persistence.OneToMany;
import com.old.silence.content.domain.enums.codegen.BuildTool;
import com.old.silence.content.domain.enums.codegen.ProjectLanguage;
import com.old.silence.content.domain.enums.codegen.ProjectType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;
import java.util.List;

/**
 * @author moryzang
 */
@Entity
public class CodeGenProject extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    private String projectName;

    private ProjectType projectType;

    private String displayName;

    private String description;

    private String baseDirectory;

    private String repoUrl;

    private String owner;

    private ProjectLanguage language;

    private BuildTool buildTool;

    @OneToMany(mappedBy = "codeGenProject")
    private List<CodeGenProjectModule> codeGenProjectModules;

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public ProjectType getProjectType() {
        return projectType;
    }

    public void setProjectType(ProjectType projectType) {
        this.projectType = projectType;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getBaseDirectory() {
        return baseDirectory;
    }

    public void setBaseDirectory(String baseDirectory) {
        this.baseDirectory = baseDirectory;
    }

    public String getRepoUrl() {
        return repoUrl;
    }

    public void setRepoUrl(String repoUrl) {
        this.repoUrl = repoUrl;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public ProjectLanguage getLanguage() {
        return language;
    }

    public void setLanguage(ProjectLanguage language) {
        this.language = language;
    }

    public BuildTool getBuildTool() {
        return buildTool;
    }

    public void setBuildTool(BuildTool buildTool) {
        this.buildTool = buildTool;
    }

    public List<CodeGenProjectModule> getCodeGenProjectModules() {
        return codeGenProjectModules;
    }

    public void setCodeGenProjectModules(List<CodeGenProjectModule> codeGenProjectModules) {
        this.codeGenProjectModules = codeGenProjectModules;
    }
}
