package com.old.silence.content.domain.model.codegen;

import jakarta.persistence.Entity;

import java.math.BigInteger;

import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

/**
 * @author moryzang
 */
@Entity
public class CodeGenProjectModule extends AbstractAutoGeneratedIdAuditable<BigInteger>{

    private BigInteger projectId;

    private BigInteger moduleId;

    public BigInteger getProjectId() {
        return projectId;
    }

    public void setProjectId(BigInteger projectId) {
        this.projectId = projectId;
    }

    public BigInteger getModuleId() {
        return moduleId;
    }

    public void setModuleId(BigInteger moduleId) {
        this.moduleId = moduleId;
    }
}
