package com.old.silence.content.domain.model.codegen;

import jakarta.persistence.Entity;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

/**
 * @author moryzang
 */
@Entity
public class CodeGenProjectModule extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    private BigInteger projectId;

    private BigInteger moduleId;

    @ManyToOne(optional = false)
    @JoinColumn(name = "project_id")
    private CodeGenProject codeGenProject;

    @ManyToOne(optional = false)
    @JoinColumn(name = "module_id")
    private CodeGenModule codeGenModule;


    public BigInteger getProjectId() {
        return projectId;
    }

    public void setProjectId(BigInteger projectId) {
        this.projectId = projectId;
    }

    public BigInteger getModuleId() {
        return moduleId;
    }

    public void setModuleId(BigInteger moduleId) {
        this.moduleId = moduleId;
    }

    public CodeGenProject getCodeGenProject() {
        return codeGenProject;
    }

    public void setCodeGenProject(CodeGenProject codeGenProject) {
        this.codeGenProject = codeGenProject;
    }

    public CodeGenModule getCodeGenModule() {
        return codeGenModule;
    }

    public void setCodeGenModule(CodeGenModule codeGenModule) {
        this.codeGenModule = codeGenModule;
    }
}
