package com.old.silence.content.domain.model.codegen;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;

import java.math.BigInteger;

import com.old.silence.content.domain.enums.codegen.ModuleType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

/**
 * @author moryzang
 */
@Entity
public class CodeGenModule extends AbstractAutoGeneratedIdAuditable<BigInteger>{

    private String moduleName;

    private String displayName;

    private String description;

    private ModuleType moduleType;

    private String basePackage;

    private String outDirectory;

    @Column(name = "is_enabled")
    private Boolean enabled;

    public String getModuleName() {
        return moduleName;
    }

    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ModuleType getModuleType() {
        return moduleType;
    }

    public void setModuleType(ModuleType moduleType) {
        this.moduleType = moduleType;
    }

    public String getBasePackage() {
        return basePackage;
    }

    public void setBasePackage(String basePackage) {
        this.basePackage = basePackage;
    }

    public String getOutDirectory() {
        return outDirectory;
    }

    public void setOutDirectory(String outDirectory) {
        this.outDirectory = outDirectory;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}
