package com.old.silence.content.domain.model.codegen;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.OneToMany;

import java.math.BigInteger;
import java.util.List;

import com.old.silence.content.domain.enums.codegen.ModuleType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

/**
 * @author moryzang
 */
@Entity
public class CodeGenModule extends AbstractAutoGeneratedIdAuditable<BigInteger>{

    private String moduleName;

    private String modulePackageName;

    private String displayName;

    private String description;

    private ModuleType moduleType;

    @Column(name = "is_enabled")
    private Boolean enabled;

    @OneToMany(mappedBy = "codeGenModule")
    private List<CodeGenProjectModule> codeGenProjectModules;

    public String getModuleName() {
        return moduleName;
    }

    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    public String getModulePackageName() {
        return modulePackageName;
    }

    public void setModulePackageName(String modulePackageName) {
        this.modulePackageName = modulePackageName;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ModuleType getModuleType() {
        return moduleType;
    }

    public void setModuleType(ModuleType moduleType) {
        this.moduleType = moduleType;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public List<CodeGenProjectModule> getCodeGenProjectModules() {
        return codeGenProjectModules;
    }

    public void setCodeGenProjectModules(List<CodeGenProjectModule> codeGenProjectModules) {
        this.codeGenProjectModules = codeGenProjectModules;
    }
}
