package com.old.silence.content.domain.model.codegen;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

/**
 * 代码文件规格实体
 * 持久化代码文件生成的元数据配置，支持动态管理而无需重新编译
 *
 * @author moryzang
 */
@Entity
public class CodeFileSpec extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    private String templateName;

    private String moduleType;

    private String packageSuffix;

    private String relativeDir;

    private String fileNameSuffix;

    private String fileTypeTag;

    private String generationCondition;

    private String endpointNames;

    private String displayName;

    private String description;

    private Integer version;

    @Column(name = "is_enabled")
    private Boolean enabled;


    public String getTemplateName() {
        return templateName;
    }

    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    public String getModuleType() {
        return moduleType;
    }

    public void setModuleType(String moduleType) {
        this.moduleType = moduleType;
    }

    public String getPackageSuffix() {
        return packageSuffix;
    }

    public void setPackageSuffix(String packageSuffix) {
        this.packageSuffix = packageSuffix;
    }

    public String getRelativeDir() {
        return relativeDir;
    }

    public void setRelativeDir(String relativeDir) {
        this.relativeDir = relativeDir;
    }

    public String getFileNameSuffix() {
        return fileNameSuffix;
    }

    public void setFileNameSuffix(String fileNameSuffix) {
        this.fileNameSuffix = fileNameSuffix;
    }

    public String getFileTypeTag() {
        return fileTypeTag;
    }

    public void setFileTypeTag(String fileTypeTag) {
        this.fileTypeTag = fileTypeTag;
    }

    public String getGenerationCondition() {
        return generationCondition;
    }

    public void setGenerationCondition(String generationCondition) {
        this.generationCondition = generationCondition;
    }

    public String getEndpointNames() {
        return endpointNames;
    }

    public void setEndpointNames(String endpointNames) {
        this.endpointNames = endpointNames;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    @Override
    public String toString() {
        return "CodeFileSpec{" +
                "id=" + getId() +
                ", templateName='" + templateName + '\'' +
                ", moduleType='" + moduleType + '\'' +
                ", enabled=" + enabled +
                '}';
    }
}
