package com.old.silence.content.domain.model.codegen;

import jakarta.persistence.Entity;

import com.old.silence.content.domain.enums.codegen.TemplateType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

/**
 * freemarker模板表实体类
 *
 * @author moryzang
 */
@Entity
public class FreemarkerTemplates extends AbstractAutoGeneratedIdAuditable<BigInteger> {
    private static final long serialVersionUID = 1L;

    /**
     * 模块id
     */
    private BigInteger moduleId;

    /**
     * 模板名称
     */
    private String templateName;

    /**
     * 模板类型
     */
    private TemplateType templateType;

    /**
     * 模板内容
     */
    private String content;

    /**
     * 描述
     */
    private String description;



    public BigInteger getModuleId() {
        return this.moduleId;
    }

    public void setModuleId(BigInteger moduleId) {
        this.moduleId = moduleId;
    }
    public String getTemplateName() {
        return this.templateName;
    }

    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }
    public TemplateType getTemplateType() {
        return this.templateType;
    }

    public void setTemplateType(TemplateType templateType) {
        this.templateType = templateType;
    }
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}