package com.old.silence.content.domain.model.poetry;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import com.old.silence.content.domain.enums.QuestionType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

@Entity
public class PoetryQuizQuestions extends AbstractAutoGeneratedIdAuditable<BigInteger> {
    private BigInteger contentId;
    private QuestionType questionType;
    private String questionStem;
    private String questionData;
    private String correctAnswer;
    private String explanation;
    private Long difficulty;
    private String hints;
    @Column(name = "is_enable")
    private Boolean enable;


    public BigInteger getContentId() {
        return this.contentId;
    }

    public void setContentId(BigInteger contentId) {
        this.contentId = contentId;
    }

    public QuestionType getQuestionType() {
        return this.questionType;
    }

    public void setQuestionType(QuestionType questionType) {
        this.questionType = questionType;
    }

    public String getQuestionStem() {
        return this.questionStem;
    }

    public void setQuestionStem(String questionStem) {
        this.questionStem = questionStem;
    }

    public String getQuestionData() {
        return this.questionData;
    }

    public void setQuestionData(String questionData) {
        this.questionData = questionData;
    }

    public String getCorrectAnswer() {
        return this.correctAnswer;
    }

    public void setCorrectAnswer(String correctAnswer) {
        this.correctAnswer = correctAnswer;
    }

    public String getExplanation() {
        return this.explanation;
    }

    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }

    public Long getDifficulty() {
        return this.difficulty;
    }

    public void setDifficulty(Long difficulty) {
        this.difficulty = difficulty;
    }

    public String getHints() {
        return this.hints;
    }

    public void setHints(String hints) {
        this.hints = hints;
    }

    public Boolean getEnable() {
        return enable;
    }

    public void setEnable(Boolean enable) {
        this.enable = enable;
    }
}