package com.old.silence.content.domain.model.poetry;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

@Entity
public class PoetryGrade extends AbstractAutoGeneratedIdAuditable<BigInteger> {
    private String code;
    private String name;
    private String description;
    @Column(name = "is_enabled")
    private Boolean enabled;


    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}