package com.old.silence.content.domain.model.poetry;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.old.silence.content.domain.enums.StudyMode;
import com.old.silence.content.domain.enums.StudyStatus;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;
import java.time.LocalTime;

@Entity
public class PoetryUserStudySetting extends AbstractAutoGeneratedIdAuditable<BigInteger> {
    private BigInteger userId;
    private BigInteger gradeId;
    private BigInteger subCategoryId;
    private Long totalCount;
    private Long dailyNewCount;
    private Long dailyReviewCount;
    private StudyMode studyMode;
    private StudyStatus status;
    @JsonFormat(pattern = "HH:mm")
    private LocalTime studyReminderTime;
    @Column(name = "is_enable_dark_mode")
    private Boolean enableDarkMode;
    private Long studySessionMinutes;


    public BigInteger getUserId() {
        return this.userId;
    }

    public void setUserId(BigInteger userId) {
        this.userId = userId;
    }

    public BigInteger getGradeId() {
        return gradeId;
    }

    public void setGradeId(BigInteger gradeId) {
        this.gradeId = gradeId;
    }

    public BigInteger getSubCategoryId() {
        return subCategoryId;
    }

    public void setSubCategoryId(BigInteger subCategoryId) {
        this.subCategoryId = subCategoryId;
    }

    public Long getTotalCount() {
        return totalCount;
    }

    public void setTotalCount(Long totalCount) {
        this.totalCount = totalCount;
    }

    public Long getDailyNewCount() {
        return this.dailyNewCount;
    }

    public void setDailyNewCount(Long dailyNewItems) {
        this.dailyNewCount = dailyNewItems;
    }

    public Long getDailyReviewCount() {
        return this.dailyReviewCount;
    }

    public StudyMode getStudyMode() {
        return studyMode;
    }

    public void setStudyMode(StudyMode studyContentType) {
        this.studyMode = studyContentType;
    }

    public StudyStatus getStatus() {
        return status;
    }

    public void setStatus(StudyStatus status) {
        this.status = status;
    }

    public void setDailyReviewCount(Long dailyReviewItems) {
        this.dailyReviewCount = dailyReviewItems;
    }

    public LocalTime getStudyReminderTime() {
        return this.studyReminderTime;
    }

    public void setStudyReminderTime(LocalTime studyReminderTime) {
        this.studyReminderTime = studyReminderTime;
    }

    public Boolean getEnableDarkMode() {
        return this.enableDarkMode;
    }

    public void setEnableDarkMode(Boolean enableDarkMode) {
        this.enableDarkMode = enableDarkMode;
    }

    public Long getStudySessionMinutes() {
        return this.studySessionMinutes;
    }

    public void setStudySessionMinutes(Long studySessionMinutes) {
        this.studySessionMinutes = studySessionMinutes;
    }
}