package com.old.silence.content.domain.model.poetry;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import com.old.silence.content.domain.enums.PromptTemplateType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;
@Entity
public class PromptTemplate extends AbstractAutoGeneratedIdAuditable<BigInteger> {
    private String templateName;
    private String templateCode;
    private PromptTemplateType templateType;
    private BigInteger subCategoryId;
    private String templateContent;
    private String variableDefinitions;
    private String exampleOutput;
    private String difficultySettings;
    private String questionTypes;
    private String version;
    @Column(name = "is_active")
    private Boolean active;
    private Long sortOrder;


    public String getTemplateName() {
        return templateName;
    }

    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    public String getTemplateCode() {
        return templateCode;
    }

    public void setTemplateCode(String templateCode) {
        this.templateCode = templateCode;
    }

    public PromptTemplateType getTemplateType() {
        return templateType;
    }

    public void setTemplateType(PromptTemplateType templateType) {
        this.templateType = templateType;
    }

    public BigInteger getSubCategoryId() {
        return subCategoryId;
    }

    public void setSubCategoryId(BigInteger subCategoryId) {
        this.subCategoryId = subCategoryId;
    }

    public String getTemplateContent() {
        return templateContent;
    }

    public void setTemplateContent(String templateContent) {
        this.templateContent = templateContent;
    }

    public String getVariableDefinitions() {
        return variableDefinitions;
    }

    public void setVariableDefinitions(String variableDefinitions) {
        this.variableDefinitions = variableDefinitions;
    }

    public String getExampleOutput() {
        return exampleOutput;
    }

    public void setExampleOutput(String exampleOutput) {
        this.exampleOutput = exampleOutput;
    }

    public String getDifficultySettings() {
        return difficultySettings;
    }

    public void setDifficultySettings(String difficultySettings) {
        this.difficultySettings = difficultySettings;
    }

    public String getQuestionTypes() {
        return questionTypes;
    }

    public void setQuestionTypes(String questionTypes) {
        this.questionTypes = questionTypes;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Long getSortOrder() {
        return sortOrder;
    }

    public void setSortOrder(Long sortOrder) {
        this.sortOrder = sortOrder;
    }
}