package com.old.silence.content.domain.model.poetry;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import com.old.silence.content.domain.enums.PromptFormatType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

@Entity
public class PromptCommonFormat extends AbstractAutoGeneratedIdAuditable<BigInteger> {
    private String formatName;
    private String formatContent;
    private PromptFormatType formatType;
    private String description;
    @Column(name = "is_active")
    private Boolean active;

    public String getFormatName() {
        return formatName;
    }

    public void setFormatName(String formatName) {
        this.formatName = formatName;
    }

    public String getFormatContent() {
        return formatContent;
    }

    public void setFormatContent(String formatContent) {
        this.formatContent = formatContent;
    }

    public PromptFormatType getFormatType() {
        return formatType;
    }

    public void setFormatType(PromptFormatType formatType) {
        this.formatType = formatType;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }
}