package com.old.silence.content.domain.model.tournament;

import java.math.BigInteger;

import com.old.silence.content.domain.enums.tournament.TournamentParticipantType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdLogicalDeletionAuditable;

/**
 * 分组记录
 *
 * @author moryzang
 */
public class TournamentGroupRecord extends AbstractAutoGeneratedIdLogicalDeletionAuditable<BigInteger> {

    /**
     * 分组id
     */
    private BigInteger groupId;

    /**
     * 参赛单位ID
     */
    private String participantId;

    /**
     * 参赛单位类型
     */
    private TournamentParticipantType participantType;

    public BigInteger getGroupId() {
        return groupId;
    }

    public void setGroupId(BigInteger groupId) {
        this.groupId = groupId;
    }

    public String getParticipantId() {
        return participantId;
    }

    public void setParticipantId(String participantId) {
        this.participantId = participantId;
    }

    public TournamentParticipantType getParticipantType() {
        return participantType;
    }

    public void setParticipantType(TournamentParticipantType participantType) {
        this.participantType = participantType;
    }
}
