package com.old.silence.content.domain.model.tournament;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.Instant;

import com.old.silence.content.domain.enums.tournament.TournamentParticipantType;
import com.old.silence.content.domain.enums.tournament.TournamentParticipantStatus;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdLogicalDeletionAuditable;

/**
 * 参赛记录表 - 赛事维度
 *
 * @author moryzang
 */
public class TournamentParticipationRecord extends AbstractAutoGeneratedIdLogicalDeletionAuditable<BigInteger> {

    /**
     * 玩法ID
     */
    private BigInteger eventGameId;

    /**
     * 参赛单位ID
     */
    private String participantId;

    /**
     * 参赛单位类型
     */
    private TournamentParticipantType participantType;

    /**
     * 参赛状态
     */
    private TournamentParticipantStatus status;

    /**
     * 报名时间
     */
    private Instant registrationTime;

    /**
     * 总得分
     */
    private BigDecimal totalScore;

    public BigInteger getEventGameId() {
        return eventGameId;
    }

    public void setEventGameId(BigInteger eventGameId) {
        this.eventGameId = eventGameId;
    }

    public String getParticipantId() {
        return participantId;
    }

    public void setParticipantId(String participantId) {
        this.participantId = participantId;
    }

    public TournamentParticipantType getParticipantType() {
        return participantType;
    }

    public void setParticipantType(TournamentParticipantType participantType) {
        this.participantType = participantType;
    }

    public TournamentParticipantStatus getStatus() {
        return status;
    }

    public void setStatus(TournamentParticipantStatus status) {
        this.status = status;
    }

    public Instant getRegistrationTime() {
        return registrationTime;
    }

    public void setRegistrationTime(Instant registrationTime) {
        this.registrationTime = registrationTime;
    }

    public BigDecimal getTotalScore() {
        return totalScore;
    }

    public void setTotalScore(BigDecimal totalScore) {
        this.totalScore = totalScore;
    }
}
