package com.old.silence.content.domain.model.tournament;

import java.math.BigInteger;

import com.old.silence.content.domain.enums.tournament.TournamentRobotInstanceType;
import com.old.silence.content.domain.enums.tournament.TournamentRobotStatus;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdLogicalDeletionAuditable;

/**
 * 赛事机器人实例
 * @author moryzang
 */
public class TournamentRobotInstance extends AbstractAutoGeneratedIdLogicalDeletionAuditable<BigInteger> {

    /**
     * 玩法ID
     */
    private BigInteger eventGameId;

    /**
     * 模板id
     */
    private BigInteger templateId;

    /**
     * 机器人类型
     */
    private TournamentRobotInstanceType robotInstanceType;

    /**
     * 机器人id
     */
    private String robotId;

    /**
     * 机器人名称
     */
    private String nickname;

    /**
     * 机器人头像
     */
    private String avatarUrl;

    /**
     * 机器人状态
     */
    private TournamentRobotStatus status;

    public BigInteger getEventGameId() {
        return eventGameId;
    }

    public void setEventGameId(BigInteger eventGameId) {
        this.eventGameId = eventGameId;
    }

    public BigInteger getTemplateId() {
        return templateId;
    }

    public void setTemplateId(BigInteger templateId) {
        this.templateId = templateId;
    }

    public TournamentRobotInstanceType getRobotInstanceType() {
        return robotInstanceType;
    }

    public void setRobotInstanceType(TournamentRobotInstanceType robotInstanceType) {
        this.robotInstanceType = robotInstanceType;
    }

    public String getRobotId() {
        return robotId;
    }

    public void setRobotId(String robotId) {
        this.robotId = robotId;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    public TournamentRobotStatus getStatus() {
        return status;
    }

    public void setStatus(TournamentRobotStatus status) {
        this.status = status;
    }
}
