package com.old.silence.content.domain.model.tournament;

import java.math.BigInteger;
import java.time.LocalDate;

import com.old.silence.content.domain.enums.tournament.TournamentStageType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdLogicalDeletionAuditable;

/**
 * 赛事分组表
 *
 * @author moryzang
 */
public class TournamentGroup extends AbstractAutoGeneratedIdLogicalDeletionAuditable<BigInteger> {

    /**
     * 玩法ID
     */
    private BigInteger eventGameId;

    /**
     * 场次类型
     */
    private TournamentStageType stageType;

    /**
     * 场次号
     */
    private Integer stageNumber;

    /**
     * 分组日期
     */
    private LocalDate groupDate;

    /**
     * 组号
     */
    private Integer groupNumber;

    /**
     * 段位名称
     */
    private String tierName;

    /**
     * 段位顺序
     */
    private Integer tierOrder;

    public BigInteger getEventGameId() {
        return eventGameId;
    }

    public void setEventGameId(BigInteger eventGameId) {
        this.eventGameId = eventGameId;
    }

    public TournamentStageType getStageType() {
        return stageType;
    }

    public void setStageType(TournamentStageType stageType) {
        this.stageType = stageType;
    }

    public Integer getStageNumber() {
        return stageNumber;
    }

    public void setStageNumber(Integer stageNumber) {
        this.stageNumber = stageNumber;
    }

    public LocalDate getGroupDate() {
        return groupDate;
    }

    public void setGroupDate(LocalDate groupDate) {
        this.groupDate = groupDate;
    }

    public Integer getGroupNumber() {
        return groupNumber;
    }

    public void setGroupNumber(Integer groupNumber) {
        this.groupNumber = groupNumber;
    }

    public String getTierName() {
        return tierName;
    }

    public void setTierName(String tierName) {
        this.tierName = tierName;
    }

    public Integer getTierOrder() {
        return tierOrder;
    }

    public void setTierOrder(Integer tierOrder) {
        this.tierOrder = tierOrder;
    }

}
