package com.old.silence.content.domain.model.tournament;


import java.math.BigDecimal;
import java.math.BigInteger;

import com.old.silence.content.domain.enums.tournament.TournamentParticipantType;
import com.old.silence.content.domain.enums.tournament.TournamentScoreType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdLogicalDeletionAuditable;

/**
 * 得分记录表 - 明细
 *
 * @author moryzang
 */
public class TournamentScoreRecord extends AbstractAutoGeneratedIdLogicalDeletionAuditable<BigInteger> {

    /**
     * 玩法ID
     */
    private BigInteger eventGameId;

    /**
     * 参赛单位ID
     */
    private String participantId;

    /**
     * 参赛单位类型
     */
    private TournamentParticipantType participantType;


    private TournamentScoreType scoreType;

    /**
     * 周期号
     */
    private Integer cycleNumber;

    /**
     * 片号
     */
    private Integer segmentNumber;

    /**
     * 场次号
     */
    private Integer stageNumber;

    /**
     * 分组ID
     */
    private BigInteger groupId;



    /**
     * 得分
     */
    private BigDecimal score;

    public BigInteger getEventGameId() {
        return eventGameId;
    }

    public void setEventGameId(BigInteger eventGameId) {
        this.eventGameId = eventGameId;
    }

    public String getParticipantId() {
        return participantId;
    }

    public void setParticipantId(String participantId) {
        this.participantId = participantId;
    }

    public TournamentParticipantType getParticipantType() {
        return participantType;
    }

    public void setParticipantType(TournamentParticipantType participantType) {
        this.participantType = participantType;
    }

    public TournamentScoreType getScoreType() {
        return scoreType;
    }

    public void setScoreType(TournamentScoreType scoreType) {
        this.scoreType = scoreType;
    }

    public Integer getCycleNumber() {
        return cycleNumber;
    }

    public void setCycleNumber(Integer cycleNumber) {
        this.cycleNumber = cycleNumber;
    }

    public Integer getSegmentNumber() {
        return segmentNumber;
    }

    public void setSegmentNumber(Integer segmentNumber) {
        this.segmentNumber = segmentNumber;
    }

    public Integer getStageNumber() {
        return stageNumber;
    }

    public void setStageNumber(Integer stageNumber) {
        this.stageNumber = stageNumber;
    }

    public BigInteger getGroupId() {
        return groupId;
    }

    public void setGroupId(BigInteger groupId) {
        this.groupId = groupId;
    }

    public BigDecimal getScore() {
        return score;
    }

    public void setScore(BigDecimal score) {
        this.score = score;
    }
}
