package com.old.silence.content.domain.model.tournament;

import com.old.silence.content.domain.enums.tournament.TournamentTaskStatus;
import com.old.silence.content.domain.enums.tournament.TournamentTaskType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;


import java.math.BigInteger;
import java.time.Instant;

/**
 * 赛事自定义任务调度表
 *
 * @author moryzang
 */
public class TournamentTask extends AbstractAutoGeneratedIdAuditable<BigInteger> {

   

    /**
     * 赛事ID
     */
    private BigInteger tournamentId;

    /**
     * 任务类型
     */
    private TournamentTaskType taskType;

    /**
     * 期号
     */
    private Integer periodNo;

    /**
     * 任务触发时间
     */
    private Instant triggerTime;

    /**
     * 任务状态
     */
    private TournamentTaskStatus status;

    /**
     * 重试次数
     */
    private Integer retryCount;

    /**
     * 前置任务ID
     */
    private BigInteger dependsOnTaskId;

    /**
     * 前置任务需要达到的状态
     */
    private TournamentTaskStatus dependsOnStatus;

    /**
     * 任务执行链路追踪ID
     */
    private String runTraceId;


    public BigInteger getTournamentId() {
        return tournamentId;
    }

    public void setTournamentId(BigInteger tournamentId) {
        this.tournamentId = tournamentId;
    }

    public TournamentTaskType getTaskType() {
        return taskType;
    }

    public void setTaskType(TournamentTaskType taskType) {
        this.taskType = taskType;
    }

    public Integer getPeriodNo() {
        return periodNo;
    }

    public void setPeriodNo(Integer periodNo) {
        this.periodNo = periodNo;
    }

    public Instant getTriggerTime() {
        return triggerTime;
    }

    public void setTriggerTime(Instant triggerTime) {
        this.triggerTime = triggerTime;
    }

    public TournamentTaskStatus getStatus() {
        return status;
    }

    public void setStatus(TournamentTaskStatus status) {
        this.status = status;
    }

    public Integer getRetryCount() {
        return retryCount;
    }

    public void setRetryCount(Integer retryCount) {
        this.retryCount = retryCount;
    }

    public BigInteger getDependsOnTaskId() {
        return dependsOnTaskId;
    }

    public void setDependsOnTaskId(BigInteger dependsOnTaskId) {
        this.dependsOnTaskId = dependsOnTaskId;
    }

    public TournamentTaskStatus getDependsOnStatus() {
        return dependsOnStatus;
    }

    public void setDependsOnStatus(TournamentTaskStatus dependsOnStatus) {
        this.dependsOnStatus = dependsOnStatus;
    }

    public String getRunTraceId() {
        return runTraceId;
    }

    public void setRunTraceId(String runTraceId) {
        this.runTraceId = runTraceId;
    }

}
