package ${packageName};

import jakarta.persistence.Entity;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

<#if hasInstantType>import java.time.Instant;
</#if>
<#if hasBigDecimalType>import java.math.BigDecimal;
</#if>
<#if hasBigIntegerType>import java.math.BigInteger;
</#if>
@Entity
public class ${className} extends AbstractAutoGeneratedIdAuditable<${primaryType}> {
    <#list columnInfos as column>
        <#if !column.primaryKey>
    private ${getJavaType(column)} ${toCamelCase(column.fieldName, false)};
        </#if>
    </#list>

    <#-- 关联关系 -->
    <#list tableInfo.foreignKeys as fk>
        <#assign fieldName = toCamelCase(fk.referencedTable, false)>
        <#assign refClassName = toCamelCase(fk.referencedTable, true)>
    @OneToMany(mappedBy = "${toCamelCase(tableInfo.tableName, false)}")
    private List<${refClassName}> ${fieldName}List;
    </#list>

    <#-- Getter和Setter方法 -->
    <#list columnInfos as column>
        <#if !column.primaryKey>
    public ${getJavaType(column)} get${toCamelCase(column.fieldName, true)}() {
        return this.${toCamelCase(column.fieldName, false)};
    }

    public void set${toCamelCase(column.fieldName, true)}(${getJavaType(column)} ${toCamelCase(column.fieldName, false)}) {
        this.${toCamelCase(column.fieldName, false)} = ${toCamelCase(column.fieldName, false)};
    }
        </#if>
    </#list>
}