package ${packageName};

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
<#if hasMapType>
import jakarta.persistence.Convert;
</#if>
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
<#if hasMapType>
import com.old.silence.data.jdbc.core.converter.MapAttributeConverter;
</#if>

<#if enumSet?has_content>
    <#list enumSet as enumName>
        import com.old.silence.content.domain.enums.${enumName};
    </#list>
</#if>

<#if hasInstantType>
import java.time.Instant;
</#if>
<#if hasBigDecimalType>
import java.math.BigDecimal;
</#if>
<#if hasBigIntegerType>
import java.math.BigInteger;
</#if>
<#if hasMapType>
import java.util.Map;
</#if>

/**
 * ${tableInfo.comment}实体类
 *
 * @author ${authorName!"作者"}
 */
@Entity
public class ${className} extends AbstractAutoGeneratedIdAuditable<${primaryKeyType}> {
    private static final long serialVersionUID = 1L;

<#list columnInfos as column>
    <#if !column.primaryKey>
    /**
     * ${column.comment}
     */
    <#if needsColumnAnnotation(column)>
    @Column(name = "${column.originalName}")
    </#if>
    <#if isMapField(column)>
    @Convert(converter = MapAttributeConverter.class)
    </#if>
    private ${getJavaType(column)} ${toCamelCase(column.fieldName, false)};

    </#if>
</#list>

    <#-- 关联关系 -->
    <#if tableInfo.foreignKeys?? && tableInfo.foreignKeys?has_content>
    <#list tableInfo.foreignKeys as fk>
        <#assign fieldName = toCamelCase(fk.referencedTable, false)>
        <#assign refClassName = toCamelCase(fk.referencedTable, true)>
    @OneToMany(mappedBy = "${toCamelCase(tableInfo.tableName, false)}")
    private List<${refClassName}> ${fieldName}List;
    </#list>
    </#if>

    <#-- Getter和Setter方法 -->
    <#list columnInfos as column>
        <#if !column.primaryKey>
    public ${getJavaType(column)} get${toCamelCase(column.fieldName, true)}() {
        return this.${toCamelCase(column.fieldName, false)};
    }

    public void set${toCamelCase(column.fieldName, true)}(${getJavaType(column)} ${toCamelCase(column.fieldName, false)}) {
        this.${toCamelCase(column.fieldName, false)} = ${toCamelCase(column.fieldName, false)};
    }
        </#if>
    </#list>
}