spring:
  datasource:
    url: jdbc:mysql://localhost:3306/silence_content?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.old.silence.content: INFO
