package com.old.silence.content.domain.model;

import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.IdClass;
import jakarta.persistence.Transient;

import org.springframework.lang.Nullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.data.commons.domain.ExplictNewPersistable;

@Entity
@IdClass(BookContentTagId.class)
public class BookContentTag extends AbstractAutoGeneratedIdAuditable<BookContentTagId>
        implements ExplictNewPersistable<BookContentTagId> {

    @Transient
    @JsonIgnore
    private boolean newEntity = false;

    @Override
    @Nullable
    @EmbeddedId
    public BookContentTagId getId() {
        return super.getId();
    }

    @Override
    @Transient
    @JsonIgnore
    public boolean isNew() {
        return newEntity;
    }

    @Override
    public void setNew(boolean newEntity) {
        this.newEntity = newEntity;

    }
}