package com.old.silence.content.domain.model;

import jakarta.persistence.Entity;
import com.old.silence.content.domain.enums.BookStatus;
import com.old.silence.content.domain.enums.BookType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.Instant;

/**
 * 图书表实体类
 *
 * @author 老默
 */
@Entity
public class Book extends AbstractAutoGeneratedIdAuditable<BigInteger> {
    private static final long serialVersionUID = 1L;

    /**
     * 父图书ID(多册时指向第一册)
     */
    private BigInteger parentId;

    /**
     * 图书类型:1-单册书 2-多册书的主册 3-多册书的子册
     */
    private BookType bookType;

    /**
     * ISBN
     */
    private String isbn;

    /**
     * 丛书ISBN(多册书使用)
     */
    private String isbnSeries;

    /**
     * 图书名称
     */
    private String name;

    /**
     * 丛书总名称(多册书使用)
     */
    private String seriesName;

    /**
     * 册号(1,2,3...)
     */
    private Long volumeNumber;

    /**
     * 册名称(上册/下册)
     */
    private String volumeName;

    /**
     * 封面引用
     */
    private String coverImageReference;

    /**
     * 正文引用
     */
    private String contentReference;

    /**
     * 状态
     */
    private BookStatus status;

    /**
     * 发布时间
     */
    private Instant publishedAt;

    /**
     * 作者
     */
    private String author;

    /**
     * 价格
     */
    private BigDecimal price;

    /**
     * 出版社
     */
    private String press;

    /**
     * 所有者
     */
    private String owner;

    /**
     * 描述
     */
    private String description;

    /**
     * 总册数
     */
    private Long totalVolumes;

    /**
     * 排序
     */
    private Long sortOrder;


    public BigInteger getParentId() {
        return this.parentId;
    }

    public void setParentId(BigInteger parentId) {
        this.parentId = parentId;
    }

    public BookType getBookType() {
        return this.bookType;
    }

    public void setBookType(BookType bookType) {
        this.bookType = bookType;
    }

    public String getIsbn() {
        return this.isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public String getIsbnSeries() {
        return this.isbnSeries;
    }

    public void setIsbnSeries(String isbnSeries) {
        this.isbnSeries = isbnSeries;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSeriesName() {
        return this.seriesName;
    }

    public void setSeriesName(String seriesName) {
        this.seriesName = seriesName;
    }

    public Long getVolumeNumber() {
        return this.volumeNumber;
    }

    public void setVolumeNumber(Long volumeNumber) {
        this.volumeNumber = volumeNumber;
    }

    public String getVolumeName() {
        return this.volumeName;
    }

    public void setVolumeName(String volumeName) {
        this.volumeName = volumeName;
    }

    public String getCoverImageReference() {
        return this.coverImageReference;
    }

    public void setCoverImageReference(String coverImageReference) {
        this.coverImageReference = coverImageReference;
    }

    public String getContentReference() {
        return this.contentReference;
    }

    public void setContentReference(String contentReference) {
        this.contentReference = contentReference;
    }

    public BookStatus getStatus() {
        return this.status;
    }

    public void setStatus(BookStatus status) {
        this.status = status;
    }

    public Instant getPublishedAt() {
        return this.publishedAt;
    }

    public void setPublishedAt(Instant publishedAt) {
        this.publishedAt = publishedAt;
    }

    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public String getPress() {
        return this.press;
    }

    public void setPress(String press) {
        this.press = press;
    }

    public String getOwner() {
        return this.owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getTotalVolumes() {
        return this.totalVolumes;
    }

    public void setTotalVolumes(Long totalVolumes) {
        this.totalVolumes = totalVolumes;
    }

    public Long getSortOrder() {
        return this.sortOrder;
    }

    public void setSortOrder(Long sortOrder) {
        this.sortOrder = sortOrder;
    }
}