package com.old.silence.content.domain.model;

import jakarta.persistence.Entity;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

/**
 * 代码生成器-表元数据实体类
 *
 * @author 老默
 */
@Entity
public class CodeTableMeta extends AbstractAutoGeneratedIdAuditable<BigInteger> {
    private static final long serialVersionUID = 1L;

    /**
     * 表名
     */
    private String tableName;

    /**
     * 数据库Schema
     */
    private String schemaName;

    /**
     * 表注释
     */
    private String comment;

    /**
     * 完整表信息JSON(包含列、索引、外键、主键)
     */
    private String detail;

    public String getTableName() {
        return this.tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getSchemaName() {
        return this.schemaName;
    }

    public void setSchemaName(String schemaName) {
        this.schemaName = schemaName;
    }
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getDetail() {
        return this.detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

}