package com.old.silence.content.domain.model;

import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.data.jdbc.core.converter.MapAttributeConverter;

import java.math.BigInteger;
import java.util.Map;


/**
 * 代码生成器-API文档实体类
 *
 * @author 老默
 */
@Entity
public class CodeApiDocument extends AbstractAutoGeneratedIdAuditable<BigInteger> {
    private static final long serialVersionUID = 1L;

    /**
     * 对应的表名
     */
    private String tableName;

    /**
     * API文档名称
     */
    private String apiName;

    /**
     * 完整API文档JSON(包含endpoints、parameters、responses)
     */
    @Convert(converter = MapAttributeConverter.class)
    private Map<String, Object> detail;


    public String getTableName() {
        return this.tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public String getApiName() {
        return this.apiName;
    }

    public void setApiName(String apiName) {
        this.apiName = apiName;
    }

    public Map<String, Object> getDetail() {
        return detail;
    }

    public void setDetail(Map<String, Object> detail) {
        this.detail = detail;
    }
}