package com.old.silence.content.domain.model;

import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Transient;


import org.springframework.lang.Nullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.data.commons.domain.ExplictNewPersistable;

@Entity
@IdClass(ContentContentTagId.class)
public class ContentContentTag extends AbstractAutoGeneratedIdAuditable<ContentContentTagId>
        implements ExplictNewPersistable<ContentContentTagId> {

    @ManyToOne(optional = false)
    @JoinColumn(name = "content_id", referencedColumnName = "id")
    private Content content;

    @ManyToOne(optional = false)
    @JoinColumn(name = "tag_id", referencedColumnName = "id")
    private ContentTag contentTag;

    @Transient
    @JsonIgnore
    private boolean newEntity = false;

    @Override
    @Nullable
    @EmbeddedId
    public ContentContentTagId getId() {
        return super.getId();
    }
    @Override
    @Transient
    @JsonIgnore
    public boolean isNew() {
        return newEntity;
    }

    @Override
    public void setNew(boolean newEntity) {
        this.newEntity = newEntity;
    }

    public Content getContent() {
        return content;
    }

    public void setContent(Content content) {
        this.content = content;
    }

    public ContentTag getContentTag() {
        return contentTag;
    }

    public void setContentTag(ContentTag contentTag) {
        this.contentTag = contentTag;
    }
}