package com.old.silence.content.domain.model;

import jakarta.persistence.Entity;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigDecimal;
import java.math.BigInteger;

@Entity
public class ContentBook extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    private static final long serialVersionUID = -1132070674619110123L;

    private String name;

    private Byte type;

    private Byte coverImageReferenceMode;

    private String coverImageReference;

    private Byte contentReferenceMode;

    private String contentReference;

    private String isbn;

    private BigDecimal price;

    private String press;

    private String description;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Byte getType() {
        return type;
    }

    public void setType(Byte type) {
        this.type = type;
    }

    public Byte getCoverImageReferenceMode() {
        return coverImageReferenceMode;
    }

    public void setCoverImageReferenceMode(Byte coverImageReferenceMode) {
        this.coverImageReferenceMode = coverImageReferenceMode;
    }

    public String getCoverImageReference() {
        return coverImageReference;
    }

    public void setCoverImageReference(String coverImageReference) {
        this.coverImageReference = coverImageReference;
    }

    public Byte getContentReferenceMode() {
        return contentReferenceMode;
    }

    public void setContentReferenceMode(Byte contentReferenceMode) {
        this.contentReferenceMode = contentReferenceMode;
    }

    public String getContentReference() {
        return contentReference;
    }

    public void setContentReference(String contentReference) {
        this.contentReference = contentReference;
    }

    public String getIsbn() {
        return isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public String getPress() {
        return press;
    }

    public void setPress(String press) {
        this.press = press;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}