package com.old.silence.content.domain.model;

import com.fasterxml.jackson.core.io.ContentReference;
import com.old.silence.content.domain.enums.ContentStatus;
import com.old.silence.content.domain.enums.ContentType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;

import javax.persistence.Entity;
import java.math.BigInteger;
import java.time.Instant;

/**
 * @author MurrayZhang
 * @description
 */

@Entity
public class Content extends AbstractAutoGeneratedIdAuditableTenantable<BigInteger, BigInteger> {
    private static final long serialVersionUID = -5865277808442432839L;

    private String title;

    private ContentType type;

    private ContentStatus status;

    private Instant publishedAt;

    private String author;

    private String contentCode;

    private String coverImageReference;

    private CoverImageReferenceMode coverImageReferenceMode;

    private ContentReferenceMode contentReferenceMode;
    private ContentReference contentReference;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public ContentType getType() {
        return type;
    }

    public void setType(ContentType type) {
        this.type = type;
    }

    public ContentStatus getStatus() {
        return status;
    }

    public void setStatus(ContentStatus status) {
        this.status = status;
    }
}
