package com.old.silence.content.domain.model;

import jakarta.persistence.Entity;
import com.old.silence.content.domain.enums.InteractionType;
import com.old.silence.content.domain.enums.ResourceType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

@Entity
public class ContentInteractionLog extends AbstractAutoGeneratedIdAuditable<BigInteger> {
    private BigInteger fromUserId;
    private BigInteger userId;
    private BigInteger resourceId;
    private ResourceType resourceType;
    private InteractionType interactionType;
    private BigInteger parentId;
    private BigInteger rootId;

    public BigInteger getFromUserId() {
        return fromUserId;
    }

    public void setFromUserId(BigInteger fromUserId) {
        this.fromUserId = fromUserId;
    }

    public BigInteger getUserId() {
        return userId;
    }

    public void setUserId(BigInteger userId) {
        this.userId = userId;
    }

    public BigInteger getResourceId() {
        return resourceId;
    }

    public void setResourceId(BigInteger resourceId) {
        this.resourceId = resourceId;
    }

    public ResourceType getResourceType() {
        return resourceType;
    }

    public void setResourceType(ResourceType resourceType) {
        this.resourceType = resourceType;
    }

    public InteractionType getInteractionType() {
        return interactionType;
    }

    public void setInteractionType(InteractionType interactionType) {
        this.interactionType = interactionType;
    }

    public BigInteger getParentId() {
        return parentId;
    }

    public void setParentId(BigInteger parentId) {
        this.parentId = parentId;
    }

    public BigInteger getRootId() {
        return rootId;
    }

    public void setRootId(BigInteger rootId) {
        this.rootId = rootId;
    }
}