package com.old.silence.content.domain.model;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;

import java.math.BigInteger;
import java.util.List;

import com.old.silence.content.domain.enums.ContentTagType;
import com.old.silence.data.commons.domain.AbstractAuditable;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;

@Entity
public class ContentTag extends AbstractAutoGeneratedIdAuditableTenantable<BigInteger, BigInteger> {

    private String name;

    @Column(updatable = false)
    private String code;

    @Column(updatable = false)
    private ContentTagType type;

    @Column(name = "is_enabled")
    private Boolean enabled;

    private BigInteger parentId;

    private String description;

    private Long sort;

    @OneToMany(mappedBy = "contentTag")
    private List<ContentContentTag> contentContentTags;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public ContentTagType getType() {
        return type;
    }

    public void setType(ContentTagType type) {
        this.type = type;
    }

    public BigInteger getParentId() {
        return parentId;
    }

    public void setParentId(BigInteger parentId) {
        this.parentId = parentId;
    }

    public Long getSort() {
        return sort;
    }

    public void setSort(Long sort) {
        this.sort = sort;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<ContentContentTag> getContentContentTags() {
        return contentContentTags;
    }

    public void setContentContentTags(List<ContentContentTag> contentContentTags) {
        this.contentContentTags = contentContentTags;
    }
}