package com.old.silence.content.domain.model;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.MapsId;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;

import java.math.BigInteger;
import java.time.Instant;
import java.util.List;
import java.util.Map;

import com.old.silence.content.domain.enums.ContentBusinessStatus;
import com.old.silence.content.domain.enums.ContentReferenceMode;
import com.old.silence.content.domain.enums.ContentStatus;
import com.old.silence.content.domain.enums.ContentType;
import com.old.silence.content.domain.enums.CoverImageReferenceMode;
import com.old.silence.data.commons.domain.AbstractAuditable;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditableTenantable;
import com.old.silence.data.jdbc.core.converter.MapAttributeConverter;

/**
 * @author moryzang
 */

@Entity
public class Content extends AbstractAutoGeneratedIdAuditableTenantable<BigInteger, BigInteger> {
    private static final long serialVersionUID = 3767967983979698045L;

    private String title;

    private ContentStatus status;

    @Column(updatable = false)
    private ContentType type;

    private String author;

    private String coverImageReference;

    private CoverImageReferenceMode coverImageReferenceMode;

    private String source;

    @Column(updatable = false)
    private String contentCode;

    @Column(name = "is_code_display_required")
    private Boolean codeDisplayRequired;

    private Instant publishedAt;

    @Column(updatable = false)
    private String auditCode;

    @Column(updatable = false)
    private String taskCode;

    private ContentReferenceMode contentReferenceMode;

    private String contentReference;

    private String keywords;

    @Column(name = "is_need_internal_review")
    private Boolean needInternalReview;

    @Column(name = "is_sticky_top")
    private Boolean stickyTop;

    private Instant stickyTopAt;

    private Instant stickyTopExpiredAt;

    @Column(name = "is_disclosure")
    private Boolean disclosure;

    @Column(name = "is_leaf")
    private Boolean leaf;

    @Column(updatable = false)
    private BigInteger parentId;

    @Column(updatable = false)
    private BigInteger rootId;

    @Convert(converter = MapAttributeConverter.class)
    private Map<String, Object> attributes;

    private Instant expiredAt;

    private ContentBusinessStatus businessStatus;

    @OneToOne(optional = false)
    @MapsId
    @JoinColumn(name = "id")
    private ContentArticle contentArticle;

    @OneToOne(optional = false)
    @MapsId
    @JoinColumn(name = "id")
    private ContentLive contentLive;

    @OneToOne(optional = false)
    @MapsId
    @JoinColumn(name = "id")
    private ContentVideo contentVideo;

    @OneToMany(mappedBy = "content")
    private List<ContentContentTag> contentContentTags;


    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public ContentType getType() {
        return type;
    }

    public void setType(ContentType type) {
        this.type = type;
    }

    public ContentStatus getStatus() {
        return status;
    }

    public void setStatus(ContentStatus status) {
        this.status = status;
    }

    public Instant getPublishedAt() {
        return publishedAt;
    }

    public void setPublishedAt(Instant publishedAt) {
        this.publishedAt = publishedAt;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getContentCode() {
        return contentCode;
    }

    public void setContentCode(String contentCode) {
        this.contentCode = contentCode;
    }

    public String getCoverImageReference() {
        return coverImageReference;
    }

    public void setCoverImageReference(String coverImageReference) {
        this.coverImageReference = coverImageReference;
    }

    public CoverImageReferenceMode getCoverImageReferenceMode() {
        return coverImageReferenceMode;
    }

    public void setCoverImageReferenceMode(CoverImageReferenceMode coverImageReferenceMode) {
        this.coverImageReferenceMode = coverImageReferenceMode;
    }

    public ContentReferenceMode getContentReferenceMode() {
        return contentReferenceMode;
    }

    public void setContentReferenceMode(ContentReferenceMode contentReferenceMode) {
        this.contentReferenceMode = contentReferenceMode;
    }

    public String getContentReference() {
        return contentReference;
    }

    public void setContentReference(String contentReference) {
        this.contentReference = contentReference;
    }

    public String getKeywords() {
        return keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    public String getAuditCode() {
        return auditCode;
    }

    public void setAuditCode(String auditCode) {
        this.auditCode = auditCode;
    }

    public String getTaskCode() {
        return taskCode;
    }

    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode;
    }

    public BigInteger getParentId() {
        return parentId;
    }

    public void setParentId(BigInteger parentId) {
        this.parentId = parentId;
    }

    public BigInteger getRootId() {
        return rootId;
    }

    public void setRootId(BigInteger rootId) {
        this.rootId = rootId;
    }

    public Boolean getStickyTop() {
        return stickyTop;
    }

    public void setStickyTop(Boolean stickyTop) {
        this.stickyTop = stickyTop;
    }

    public Instant getStickyTopAt() {
        return stickyTopAt;
    }

    public void setStickyTopAt(Instant stickyTopAt) {
        this.stickyTopAt = stickyTopAt;
    }

    public Instant getStickyTopExpiredAt() {
        return stickyTopExpiredAt;
    }

    public void setStickyTopExpiredAt(Instant stickyTopExpiredAt) {
        this.stickyTopExpiredAt = stickyTopExpiredAt;
    }

    public Boolean getDisclosure() {
        return disclosure;
    }

    public void setDisclosure(Boolean disclosure) {
        this.disclosure = disclosure;
    }

    public Boolean getLeaf() {
        return leaf;
    }

    public void setLeaf(Boolean leaf) {
        this.leaf = leaf;
    }

    public Map<String, Object> getAttributes() {
        return attributes;
    }

    public void setAttributes(Map<String, Object> attributes) {
        this.attributes = attributes;
    }

    public ContentBusinessStatus getBusinessStatus() {
        return businessStatus;
    }

    public void setBusinessStatus(ContentBusinessStatus businessStatus) {
        this.businessStatus = businessStatus;
    }

    public ContentArticle getContentArticle() {
        return contentArticle;
    }

    public void setContentArticle(ContentArticle contentArticle) {
        this.contentArticle = contentArticle;
    }

    public ContentLive getContentLive() {
        return contentLive;
    }

    public void setContentLive(ContentLive contentLive) {
        this.contentLive = contentLive;
    }

    public ContentVideo getContentVideo() {
        return contentVideo;
    }

    public void setContentVideo(ContentVideo contentVideo) {
        this.contentVideo = contentVideo;
    }

    public List<ContentContentTag> getContentContentTags() {
        return contentContentTags;
    }

    public void setContentContentTags(List<ContentContentTag> contentContentTags) {
        this.contentContentTags = contentContentTags;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public Boolean getCodeDisplayRequired() {
        return codeDisplayRequired;
    }

    public void setCodeDisplayRequired(Boolean codeDisplayRequired) {
        this.codeDisplayRequired = codeDisplayRequired;
    }

    public Boolean getNeedInternalReview() {
        return needInternalReview;
    }

    public void setNeedInternalReview(Boolean needInternalReview) {
        this.needInternalReview = needInternalReview;
    }

    public Instant getExpiredAt() {
        return expiredAt;
    }

    public void setExpiredAt(Instant expiredAt) {
        this.expiredAt = expiredAt;
    }
}
