package com.old.silence.content.domain.model;

import jakarta.persistence.Entity;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;


@Entity
public class ContentContentTag extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    private BigInteger contentId;
    private BigInteger tagId;
    @ManyToOne(optional = false)
    @JoinColumn(name = "content_id")
    private Content content;
    @ManyToOne(optional = false)
    @JoinColumn(name = "tag_id")
    private ContentTag contentTag;

    public BigInteger getContentId() {
        return contentId;
    }

    public void setContentId(BigInteger contentId) {
        this.contentId = contentId;
    }

    public BigInteger getTagId() {
        return tagId;
    }

    public void setTagId(BigInteger tagId) {
        this.tagId = tagId;
    }

    public Content getContent() {
        return content;
    }

    public void setContent(Content content) {
        this.content = content;
    }

    public ContentTag getContentTag() {
        return contentTag;
    }

    public void setContentTag(ContentTag contentTag) {
        this.contentTag = contentTag;
    }
}