package com.old.silence.content.domain.model;

import jakarta.persistence.Entity;
import com.old.silence.content.domain.enums.InteractionType;
import com.old.silence.content.domain.enums.ResourceType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

/**
 * @author MurrayZhang
 */
@Entity
public class ContentInteractionAccumulation extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    private BigInteger resourceId;

    private ResourceType resourceType;

    private InteractionType type;

    private BigInteger accumulation;

    public BigInteger getResourceId() {
        return resourceId;
    }

    public void setResourceId(BigInteger resourceId) {
        this.resourceId = resourceId;
    }

    public ResourceType getResourceType() {
        return resourceType;
    }

    public void setResourceType(ResourceType resourceType) {
        this.resourceType = resourceType;
    }

    public InteractionType getType() {
        return type;
    }

    public void setType(InteractionType type) {
        this.type = type;
    }

    public BigInteger getAccumulation() {
        return accumulation;
    }

    public void setAccumulation(BigInteger accumulation) {
        this.accumulation = accumulation;
    }
}
