package com.old.silence.content.domain.model;

import jakarta.persistence.Entity;

import java.math.BigInteger;

import com.old.silence.content.domain.enums.ContentTagType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

@Entity
public class ContentTag extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    private static final long serialVersionUID = -6538213674472033336L;

    private ContentTagType type;

    private String name;

    private String code;

    private Boolean enabled;

    private Long sort;

    public ContentTagType getType() {
        return type;
    }

    public void setType(ContentTagType type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public Long getSort() {
        return sort;
    }

    public void setSort(Long sort) {
        this.sort = sort;
    }
}