package com.old.silence.content.domain.model;


import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import com.old.silence.content.domain.enums.EventGameRewardItemClaimType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdLogicalDeletionAuditable;
import com.old.silence.data.jdbc.core.converter.MapAttributeConverter;


import java.math.BigInteger;
import java.util.Map;

@Entity
public class EventGameRewardItem extends AbstractAutoGeneratedIdLogicalDeletionAuditable<BigInteger> {

    private static final long serialVersionUID = 1L;

    private BigInteger eventGameId;

    @ManyToOne(optional = false)
    @JoinColumn(name = "event_game_id", referencedColumnName = "id")
    private EventGame eventGame;

    private BigInteger rewardItemId;

    @OneToOne(optional = false)
    private RewardItem rewardItem;

    private BigInteger rewardRuleId;

    @OneToOne
    private MarketingRule rewardRule;

    private Long quantity;

    private Long inventoryQuantity;

    @Convert(converter = MapAttributeConverter.class)
    private Map<String, Object> attributes;

    private EventGameRewardItemClaimType claimType;

    public BigInteger getEventGameId() {
        return eventGameId;
    }

    public void setEventGameId(BigInteger eventGameId) {
        this.eventGameId = eventGameId;
    }

    public EventGame getEventGame() {
        return eventGame;
    }

    public void setEventGame(EventGame eventGame) {
        this.eventGame = eventGame;
    }

    public BigInteger getRewardItemId() {
        return rewardItemId;
    }

    public void setRewardItemId(BigInteger rewardItemId) {
        this.rewardItemId = rewardItemId;
    }

    public RewardItem getRewardItem() {
        return rewardItem;
    }

    public void setRewardItem(RewardItem rewardItem) {
        this.rewardItem = rewardItem;
    }

    public BigInteger getRewardRuleId() {
        return rewardRuleId;
    }

    public void setRewardRuleId(BigInteger rewardRuleId) {
        this.rewardRuleId = rewardRuleId;
    }

    public MarketingRule getRewardRule() {
        return rewardRule;
    }

    public void setRewardRule(MarketingRule rewardRule) {
        this.rewardRule = rewardRule;
    }

    public Long getQuantity() {
        return quantity;
    }

    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    public Long getInventoryQuantity() {
        return inventoryQuantity;
    }

    public void setInventoryQuantity(Long inventoryQuantity) {
        this.inventoryQuantity = inventoryQuantity;
    }

    public Map<String, Object> getAttributes() {
        return this.attributes;
    }

    public void setAttributes(Map<String, Object> attributes) {
        this.attributes = attributes;
    }

    public EventGameRewardItemClaimType getClaimType() {
        return claimType;
    }

    public void setClaimType(EventGameRewardItemClaimType claimType) {
        this.claimType = claimType;
    }


}
