package com.old.silence.content.domain.model;



import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;

import com.old.silence.content.domain.enums.EventGameType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdLogicalDeletionAuditable;
import com.old.silence.json.JacksonMapper;

import java.math.BigInteger;
import java.time.Instant;
import java.util.List;

/**
 * @author EX-HEXIAN004
 */
@Entity
public class EventGame extends AbstractAutoGeneratedIdLogicalDeletionAuditable<BigInteger> {

    private static final long serialVersionUID = 1L;

    private BigInteger eventId;

    @ManyToOne
    private MarketingEvent event;

    private String name;

    @Column(updatable = false)
    private EventGameType type;

    private Instant effectiveAt;

    private Instant expiresAt;

    private BigInteger entryRuleId;

    @OneToOne
    private MarketingRule entryRule;

    private String sourceIdentifier;

    private String imageUrl;

    private String attributes;

    private String eoaNo;

    @OneToMany(mappedBy = "eventGame")
    private List<EventGameRewardItem> eventGameRewardItems;

    public BigInteger getEventId() {
        return eventId;
    }

    public void setEventId(BigInteger eventId) {
        this.eventId = eventId;
    }

    public MarketingEvent getEvent() {
        return event;
    }

    public void setEvent(MarketingEvent event) {
        this.event = event;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public EventGameType getType() {
        return type;
    }

    public void setType(EventGameType type) {
        this.type = type;
    }

    public Instant getEffectiveAt() {
        return effectiveAt;
    }

    public void setEffectiveAt(Instant effectiveAt) {
        this.effectiveAt = effectiveAt;
    }

    public Instant getExpiresAt() {
        return expiresAt;
    }

    public void setExpiresAt(Instant expiresAt) {
        this.expiresAt = expiresAt;
    }

    public BigInteger getEntryRuleId() {
        return entryRuleId;
    }

    public void setEntryRuleId(BigInteger entryRuleId) {
        this.entryRuleId = entryRuleId;
    }

    public boolean validate() {
        var now = Instant.now();
        return !now.isBefore(effectiveAt) && !now.isAfter(expiresAt);
    }

    public String getSourceIdentifier() {
        return sourceIdentifier;
    }

    public void setSourceIdentifier(String sourceIdentifier) {
        this.sourceIdentifier = sourceIdentifier;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getAttributes() {
        return attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    public <T> T unwrapAttributes(Class<T> type) {
        if (attributes == null) {
            return null;
        }
        return JacksonMapper.getSharedInstance().fromJson(attributes, type);
    }

    public String getEoaNo() {
        return eoaNo;
    }

    public void setEoaNo(String eoaNo) {
        this.eoaNo = eoaNo;
    }

    public MarketingRule getEntryRule() {
        return entryRule;
    }

    public void setEntryRule(MarketingRule entryRule) {
        this.entryRule = entryRule;
    }

    public List<EventGameRewardItem> getEventGameRewardItems() {
        return eventGameRewardItems;
    }

    public void setEventGameRewardItems(List<EventGameRewardItem> eventGameRewardItems) {
        this.eventGameRewardItems = eventGameRewardItems;
    }
}
