package com.old.silence.content.domain.model;

import jakarta.persistence.Entity;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;
@Entity
public class LiveRoomOrganization extends AbstractAutoGeneratedIdAuditable<BigInteger> {
    private BigInteger liveRoomId;
    private String orgCode;


    public BigInteger getLiveRoomId() {
        return this.liveRoomId;
    }

    public void setLiveRoomId(BigInteger liveRoomId) {
        this.liveRoomId = liveRoomId;
    }
    public String getOrgCode() {
        return this.orgCode;
    }

    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }
}