package com.old.silence.content.domain.model;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;

import com.old.silence.content.domain.enums.LiveChannel;
import com.old.silence.content.domain.enums.LivePlatform;
import com.old.silence.content.domain.enums.LiveRoomType;
import com.old.silence.data.commons.annotation.LogicalDeletion;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.data.jdbc.core.converter.MapAttributeConverter;

import java.math.BigInteger;
import java.time.Instant;
import java.util.Map;

@Entity
public class LiveRoom extends AbstractAutoGeneratedIdAuditable<BigInteger> {
    private LivePlatform platform;
    private LiveChannel channel;
    private String anchorUmAccount;
    private String title;
    private String backgroundImage;
    private String shareImage;
    private String promotionImage;
    private Instant startTime;
    private Instant endTime;
    private LiveRoomType roomType;
    private String content;
    @Convert(converter = MapAttributeConverter.class)
    private Map<String, Object> attributes;
    @LogicalDeletion
    @Column(name = "is_deleted")
    private Boolean deleted;


    public LivePlatform getPlatform() {
        return platform;
    }

    public void setPlatform(LivePlatform platform) {
        this.platform = platform;
    }

    public LiveChannel getChannel() {
        return channel;
    }

    public void setChannel(LiveChannel channel) {
        this.channel = channel;
    }

    public String getAnchorUmAccount() {
        return anchorUmAccount;
    }

    public void setAnchorUmAccount(String anchorUmAccount) {
        this.anchorUmAccount = anchorUmAccount;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBackgroundImage() {
        return backgroundImage;
    }

    public void setBackgroundImage(String backgroundImage) {
        this.backgroundImage = backgroundImage;
    }

    public String getShareImage() {
        return shareImage;
    }

    public void setShareImage(String shareImage) {
        this.shareImage = shareImage;
    }

    public String getPromotionImage() {
        return promotionImage;
    }

    public void setPromotionImage(String promotionImage) {
        this.promotionImage = promotionImage;
    }

    public Instant getStartTime() {
        return startTime;
    }

    public void setStartTime(Instant startTime) {
        this.startTime = startTime;
    }

    public Instant getEndTime() {
        return endTime;
    }

    public void setEndTime(Instant endTime) {
        this.endTime = endTime;
    }

    public LiveRoomType getRoomType() {
        return roomType;
    }

    public void setRoomType(LiveRoomType roomType) {
        this.roomType = roomType;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Map<String, Object> getAttributes() {
        return attributes;
    }

    public void setAttributes(Map<String, Object> attributes) {
        this.attributes = attributes;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}