package com.old.silence.content.domain.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;

import java.math.BigInteger;

import com.old.silence.content.domain.enums.LiveBroadcasterRoleType;
import com.old.silence.content.domain.enums.LiveChannel;
import com.old.silence.content.domain.enums.LivePlatform;
import com.old.silence.data.commons.annotation.LogicalDeletion;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

@Entity
public class LiveBroadcaster extends AbstractAutoGeneratedIdAuditable<BigInteger> {
    private LivePlatform platform;
    private LiveChannel channel;
    private String channelAppid;
    private LiveBroadcasterRoleType roleType;
    private String umAccount;
    private String nickname;
    private String wechatId;
    @LogicalDeletion
    @Column(name = "is_deleted")
    private Boolean deleted;


    public LivePlatform getPlatform() {
        return platform;
    }

    public void setPlatform(LivePlatform platform) {
        this.platform = platform;
    }

    public LiveChannel getChannel() {
        return channel;
    }

    public void setChannel(LiveChannel channel) {
        this.channel = channel;
    }

    public String getChannelAppid() {
        return channelAppid;
    }

    public void setChannelAppid(String channelAppid) {
        this.channelAppid = channelAppid;
    }

    public LiveBroadcasterRoleType getRoleType() {
        return roleType;
    }

    public void setRoleType(LiveBroadcasterRoleType role) {
        this.roleType = role;
    }

    public String getUmAccount() {
        return umAccount;
    }

    public void setUmAccount(String umAccount) {
        this.umAccount = umAccount;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getWechatId() {
        return wechatId;
    }

    public void setWechatId(String wechatId) {
        this.wechatId = wechatId;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}