package com.old.silence.content.domain.model;

import jakarta.persistence.Convert;
import jakarta.persistence.Entity;


import com.old.silence.content.domain.enums.MarketingRuleType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;
import com.old.silence.data.jdbc.core.converter.MapAttributeConverter;

import java.math.BigInteger;
import java.util.Map;

/**
 * @author EX-HEXIAN004
 */
@Entity
public class MarketingRule extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    private static final long serialVersionUID = 1L;

    private String name;

    private MarketingRuleType type;

    @Convert(converter = MapAttributeConverter.class)
    private Map<String, Object> content;

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public MarketingRuleType getType() {
        return type;
    }

    public void setType(MarketingRuleType type) {
        this.type = type;
    }

    public Object getContent() {
        return content;
    }

    public <T> T unwrapContent(Class<T> type) {
        if (content == null) {
            return null;
        }

        if (!type.isAssignableFrom(content.getClass())) {
            throw new IllegalArgumentException(
                    "MarketingRule attributes type [" + content.getClass() + "] can not cast to [" + type + ']');
        }

        return type.cast(content);
    }

    public void setContent(Map<String, Object> content) {
        this.content = content;
    }
}
