package com.old.silence.content.domain.model;



import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import com.old.silence.content.domain.enums.BusinessScene;
import com.old.silence.content.domain.enums.MarketingEventStatus;
import com.old.silence.content.domain.enums.MarketingType;
import com.old.silence.content.domain.enums.ParticipantType;
import com.old.silence.content.infrastructure.persistence.converter.IbosContentAttributeConverter;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdLogicalDeletionAuditable;
import com.old.silence.data.jdbc.core.converter.MapAttributeConverter;


import java.math.BigInteger;
import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * @author EX-HEXIAN004
 */
@Entity
public class MarketingEvent extends AbstractAutoGeneratedIdLogicalDeletionAuditable<BigInteger> {

    private static final long serialVersionUID = 1L;

    private String name;

    private String code;

    private BusinessScene businessScene;

    private String displayName;

    private String description;

    private Instant startTime;

    private Instant endTime;

    private String coverUrl;

    private String backgroundImageIobsKey;

    /**
     * 活动所属机构
     * @return
     */
    private String regionCode;
    /**
     * 活动分类
     */
    private MarketingType categoryCode;

    @Column(name = "rule_content_iobs_key")
    @Convert(converter = IbosContentAttributeConverter.class)
    private String ruleContent;

    private BigInteger entryRuleId;

    @OneToOne
    private MarketingRule entryRule;

    private MarketingEventStatus status;

    /**
     * 活动参与者类型
     */
    private ParticipantType participantType;

    @OneToMany(mappedBy = "event")
    private List<EventGame> eventGames;

    @Convert(converter = MapAttributeConverter.class)
    @Column(name = "marketing_attributes")
    private Map<String, Object> attributes;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public BusinessScene getBusinessScene() {
        return businessScene;
    }

    public void setBusinessScene(BusinessScene businessScene) {
        this.businessScene = businessScene;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Instant getStartTime() {
        return startTime;
    }

    public void setStartTime(Instant startTime) {
        this.startTime = startTime;
    }

    public Instant getEndTime() {
        return endTime;
    }

    public void setEndTime(Instant endTime) {
        this.endTime = endTime;
    }

    public String getCoverUrl() {
        return coverUrl;
    }

    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl;
    }

    public BigInteger getEntryRuleId() {
        return entryRuleId;
    }

    public void setEntryRuleId(BigInteger entryRuleId) {
        this.entryRuleId = entryRuleId;
    }

    public MarketingRule getEntryRule() {
        return entryRule;
    }

    public void setEntryRule(MarketingRule entryRule) {
        this.entryRule = entryRule;
    }

    public MarketingEventStatus getStatus() {
        return status;
    }

    public void setStatus(MarketingEventStatus status) {
        this.status = status;
    }

    public List<EventGame> getEventGames() {
        return eventGames;
    }

    public void setEventGames(List<EventGame> eventGames) {
        this.eventGames = eventGames;
    }

    public String getBackgroundImageIobsKey() {
        return backgroundImageIobsKey;
    }

    public void setBackgroundImageIobsKey(String backgroundImageIobsKey) {
        this.backgroundImageIobsKey = backgroundImageIobsKey;
    }

    public String getRuleContent() {
        return ruleContent;
    }

    public void setRuleContent(String ruleContent) {
        this.ruleContent = ruleContent;
    }

    public ParticipantType getParticipantType() {
        return participantType;
    }

    public void setParticipantType(ParticipantType participantType) {
        this.participantType = participantType;
    }

    public Map<String, Object> getAttributes() {
        return attributes;
    }

    public void setAttributes(Map<String, Object> attributes) {
        this.attributes = attributes;
    }

    public boolean validate() {
        var now = Instant.now();
        if (now.isBefore(startTime) || now.isAfter(endTime)) {
            return false;
        }
        return MarketingEventStatus.PUBLISHED == status;
    }

    /**
     * 检查活动是否完全在时间段内或跨越时间段（包含等于的情况）
     * @param marketingStart
     * @param marketingEnd
     * @return
     */
    public boolean validateTimeAndStatus(Instant marketingStart, Instant marketingEnd) {
        boolean isActivityWithinOrCrossingPeriod =
                !marketingStart.isAfter(endTime) && !marketingEnd.isBefore(startTime);
        if (isActivityWithinOrCrossingPeriod) {
            return MarketingEventStatus.PUBLISHED == status;
        }

        return false;
    }

    public String getRegionCode() {
        return regionCode;
    }

    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode;
    }

    public MarketingType getCategoryCode() {
        return categoryCode;
    }

    public void setCategoryCode(MarketingType categoryCode) {
        this.categoryCode = categoryCode;
    }
}
