package com.old.silence.content.domain.model;

import jakarta.persistence.Entity;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;

import com.old.silence.content.api.vo.PoetryDailyStudyPlanView;
import com.old.silence.data.commons.domain.AbstractAuditable;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.time.Instant;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;

@Entity
public class PoetryDailyStudyPlan extends AbstractAutoGeneratedIdAuditable<BigInteger> {
    private BigInteger userId;
    private BigInteger subCategoryId;
    private LocalDate planDate;
    private String newItemIds;
    private String reviewItemIds;
    private String completedNewItems;
    private String completedReviewItems;
    private BigDecimal completionRate;

    @OneToOne(optional = false)
    @JoinColumn(name = "sub_category_id")
    private PoetryCategory poetryCategory;


    public BigInteger getUserId() {
        return this.userId;
    }

    public void setUserId(BigInteger userId) {
        this.userId = userId;
    }

    public BigInteger getSubCategoryId() {
        return subCategoryId;
    }

    public void setSubCategoryId(BigInteger subCategoryId) {
        this.subCategoryId = subCategoryId;
    }

    public LocalDate  getPlanDate() {
        return this.planDate;
    }

    public void setPlanDate(LocalDate  planDate) {
        this.planDate = planDate;
    }

    public String getNewItemIds() {
        return this.newItemIds;
    }

    public void setNewItemIds(String newItemIds) {
        this.newItemIds = newItemIds;
    }

    public String getReviewItemIds() {
        return this.reviewItemIds;
    }

    public void setReviewItemIds(String reviewItemIds) {
        this.reviewItemIds = reviewItemIds;
    }

    public String getCompletedNewItems() {
        return this.completedNewItems;
    }

    public void setCompletedNewItems(String completedNewItems) {
        this.completedNewItems = completedNewItems;
    }

    public String getCompletedReviewItems() {
        return this.completedReviewItems;
    }

    public void setCompletedReviewItems(String completedReviewItems) {
        this.completedReviewItems = completedReviewItems;
    }

    public BigDecimal getCompletionRate() {
        return this.completionRate;
    }

    public void setCompletionRate(BigDecimal completionRate) {
        this.completionRate = completionRate;
    }

    public PoetryCategory getPoetryCategory() {
        return poetryCategory;
    }

    public void setPoetryCategory(PoetryCategory poetryCategory) {
        this.poetryCategory = poetryCategory;
    }
}