package com.old.silence.content.domain.model;

import jakarta.persistence.Entity;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

@Entity
public class PoetryGradePoetryCategory extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    private BigInteger gradeId;
    private BigInteger categoryId;

    @ManyToOne
    @JoinColumn(name = "category_id")
    private PoetryCategory poetryCategory;

    public BigInteger getGradeId() {
        return gradeId;
    }

    public void setGradeId(BigInteger gradeId) {
        this.gradeId = gradeId;
    }

    public BigInteger getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(BigInteger categoryId) {
        this.categoryId = categoryId;
    }

    public PoetryCategory getPoetryCategory() {
        return poetryCategory;
    }

    public void setPoetryCategory(PoetryCategory poetryCategory) {
        this.poetryCategory = poetryCategory;
    }
}