package com.old.silence.content.domain.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

@Entity
public class PromptCommonFormat extends AbstractAutoGeneratedIdAuditable<BigInteger> {
    private String formatName;
    private String formatContent;
    private String description;
    @Column(name = "is_active")
    private Boolean active;


    public String getFormatName() {
        return this.formatName;
    }

    public void setFormatName(String formatName) {
        this.formatName = formatName;
    }

    public String getFormatContent() {
        return this.formatContent;
    }

    public void setFormatContent(String formatContent) {
        this.formatContent = formatContent;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }
}