package com.old.silence.content.domain.model;

import jakarta.persistence.Entity;
import com.old.silence.content.domain.enums.BookStatus;
import com.old.silence.content.domain.enums.BookType;
import com.old.silence.content.domain.enums.ProvisionChannel;
import com.old.silence.content.domain.enums.ProvisionScenario;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.Instant;

/**
 * 条款实体类
 *
 * @author 老默
 */
@Entity
public class Provision extends AbstractAutoGeneratedIdAuditable<BigInteger> {
    private static final long serialVersionUID = 1L;


    /**
     * 场景code
     */
    private ProvisionScenario scenarioCode;


    /**
     * 取到code
     */
    private ProvisionChannel channelCode;

    /**
     * 条款名称
     */
    private String name;


    /**
     * 条款链接
     */
    private String url;

    public ProvisionScenario getScenarioCode() {
        return scenarioCode;
    }

    public void setScenarioCode(ProvisionScenario scenarioCode) {
        this.scenarioCode = scenarioCode;
    }

    public ProvisionChannel getChannelCode() {
        return channelCode;
    }

    public void setChannelCode(ProvisionChannel channelCode) {
        this.channelCode = channelCode;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }
}