package com.old.silence.content.domain.model;




import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;

import com.old.silence.content.domain.enums.RewardItemStatus;
import com.old.silence.content.domain.enums.RewardItemType;
import com.old.silence.content.domain.enums.TimeCalculationMethod;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdLogicalDeletionAuditable;
import com.old.silence.data.jdbc.core.converter.MapAttributeConverter;

import java.math.BigInteger;
import java.util.List;
import java.util.Map;

/**
 * @author EX-HEXIAN004
 */
@Entity
public class RewardItem extends AbstractAutoGeneratedIdLogicalDeletionAuditable<BigInteger> {

    private static final long serialVersionUID = 1L;

    private String name;

    private String displayName;

    private String description;

    private RewardItemType type;

    private Long quantity;

    private Long inventoryQuantity;

    private String iconKey;

    private String iconUrl;

    private String referenceId;

    private RewardItemStatus status;

    @Column(name = "is_claim_required")
    private Boolean claimRequired;

    private TimeCalculationMethod expirationTimeCalculationMethod;

    private String expirationTimeCalculationValue;

    @Convert(converter = MapAttributeConverter.class)
    private Map<String, Object> attributes;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public RewardItemType getType() {
        return type;
    }

    public void setType(RewardItemType type) {
        this.type = type;
    }

    public Long getQuantity() {
        return quantity;
    }

    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    public Long getInventoryQuantity() {
        return inventoryQuantity;
    }

    public void setInventoryQuantity(Long inventoryQuantity) {
        this.inventoryQuantity = inventoryQuantity;
    }

    public String getIconKey() {
        return iconKey;
    }

    public void setIconKey(String iconKey) {
        this.iconKey = iconKey;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public String getReferenceId() {
        return referenceId;
    }

    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId;
    }

    public RewardItemStatus getStatus() {
        return status;
    }

    public void setStatus(RewardItemStatus status) {
        this.status = status;
    }

    public Boolean getClaimRequired() {
        return claimRequired;
    }

    public void setClaimRequired(Boolean claimRequired) {
        this.claimRequired = claimRequired;
    }

    public TimeCalculationMethod getExpirationTimeCalculationMethod() {
        return expirationTimeCalculationMethod;
    }

    public void setExpirationTimeCalculationMethod(TimeCalculationMethod expirationTimeCalculationMethod) {
        this.expirationTimeCalculationMethod = expirationTimeCalculationMethod;
    }

    public String getExpirationTimeCalculationValue() {
        return expirationTimeCalculationValue;
    }

    public void setExpirationTimeCalculationValue(String expirationTimeCalculationValue) {
        this.expirationTimeCalculationValue = expirationTimeCalculationValue;
    }

    public Map<String, Object> getAttributes() {
        return attributes;
    }

    public <T> T unwrapAttributes(Class<T> type) {
        if (attributes == null) {
            return null;
        }
        if (!attributes.getClass().isAssignableFrom(type)) {
            throw new IllegalArgumentException(
                    "RewardItem attributes type [" + attributes.getClass() + "] can not cast to [" + type + ']');
        }

        return type.cast(attributes);
    }

    public void setAttributes(Map<String, Object> attributes) {
        this.attributes = attributes;
    }
}
