package com.old.silence.content.domain.model;



import jakarta.persistence.Entity;

import com.old.silence.content.api.config.TournamentConfigurationProperties;
import com.old.silence.content.domain.enums.tournament.TournamentRobotInstanceType;
import com.old.silence.content.domain.enums.tournament.TournamentRobotStatus;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdLogicalDeletionAuditable;

import java.math.BigInteger;

/**
 * 赛事机器人实例
 * @author EX-GUOWEI869
 */
@Entity
public class TournamentRobotInstance extends AbstractAutoGeneratedIdLogicalDeletionAuditable<BigInteger> {

    /**
     * 玩法ID
     */
    private BigInteger eventGameId;

    /**
     * 模板id
     */
    private BigInteger templateId;

    /**
     * 机器人类型
     */
    private TournamentRobotInstanceType robotInstanceType;

    /**
     * 机器人id
     */
    private BigInteger robotId;

    /**
     * 机器人名称
     */
    private String nickname;

    /**
     * 机器人头像
     */
    private String avatarUrl;

    /**
     * 机器人状态
     */
    private TournamentRobotStatus status;

    public BigInteger getEventGameId() {
        return eventGameId;
    }

    public void setEventGameId(BigInteger eventGameId) {
        this.eventGameId = eventGameId;
    }

    public BigInteger getTemplateId() {
        return templateId;
    }

    public void setTemplateId(BigInteger templateId) {
        this.templateId = templateId;
    }

    public TournamentRobotInstanceType getRobotInstanceType() {
        return robotInstanceType;
    }

    public void setRobotInstanceType(TournamentRobotInstanceType robotInstanceType) {
        this.robotInstanceType = robotInstanceType;
    }

    public BigInteger getRobotId() {
        return robotId;
    }

    public void setRobotId(BigInteger robotId) {
        this.robotId = robotId;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    public TournamentRobotStatus getStatus() {
        return status;
    }

    public void setStatus(TournamentRobotStatus status) {
        this.status = status;
    }

    public static TournamentRobotInstance initTournamentRobotInstance(TournamentConfigurationProperties.RobotTemplate robotTemplate) {
        var tournamentRobotInstance = new TournamentRobotInstance();
        tournamentRobotInstance.setTemplateId(robotTemplate.getTemplateId());
        tournamentRobotInstance.setRobotId(robotTemplate.getRobotId());
        tournamentRobotInstance.setNickname(robotTemplate.getNickname());
        tournamentRobotInstance.setAvatarUrl(robotTemplate.getAvatarUrl());

        tournamentRobotInstance.setRobotInstanceType(TournamentRobotInstanceType.DEFAULT);
        tournamentRobotInstance.setStatus(TournamentRobotStatus.ACTIVE);

        return tournamentRobotInstance;
    }
}
