package com.old.silence.content.domain.model;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import com.old.silence.content.api.tournament.tournament.dto.support.ExerciseScoreCoefficient;
import com.old.silence.content.domain.enums.tournament.TournamentChallengeStatus;
import com.old.silence.content.domain.enums.tournament.TournamentParticipantType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdLogicalDeletionAuditable;
import com.old.silence.data.jdbc.core.converter.MapAttributeConverter;


import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.Instant;
import java.util.Map;

/**
 * 挑战记录表 - 明细
 *
 * @author EX-GUOWEI869
 */
@Entity
public class TournamentChallengeRecord extends AbstractAutoGeneratedIdLogicalDeletionAuditable<BigInteger> {

    /**
     * 玩法ID
     */
    private BigInteger eventGameId;

    /**
     * 参赛单位ID
     */
    private BigInteger participantId;

    /**
     * 参赛单位类型
     */
    private TournamentParticipantType participantType;

    /**
     * 贡献者ID
     */
    private BigInteger contributorId;

    /**
     * 周期号
     */
    private Integer cycleNumber;

    /**
     * 片号
     */
    private Integer segmentNumber;

    /**
     * 场次号
     */
    private Integer stageNumber;

    /**
     * 分组ID
     */
    private BigInteger groupId;

    /**
     * 挑战状态
     */
    @Column(name = "challenge_status")
    private TournamentChallengeStatus status;

    /**
     * 开始时间
     */
    private Instant startTime;

    /**
     * 结束时间
     */
    private Instant endTime;

    /**
     * 基础分
     */
    private BigDecimal baseScore;

    /**
     * 最终分
     */
    private BigDecimal finalScore;

    /**
     * 运动项详情JSON
     * @see ExerciseScoreCoefficient
     */
    @Convert(converter = MapAttributeConverter.class)
    private Map<String, Object> exerciseDetails;

    public BigInteger getEventGameId() {
        return eventGameId;
    }

    public void setEventGameId(BigInteger eventGameId) {
        this.eventGameId = eventGameId;
    }

    public BigInteger getParticipantId() {
        return participantId;
    }

    public void setParticipantId(BigInteger participantId) {
        this.participantId = participantId;
    }

    public TournamentParticipantType getParticipantType() {
        return participantType;
    }

    public void setParticipantType(TournamentParticipantType participantType) {
        this.participantType = participantType;
    }

    public BigInteger getContributorId() {
        return contributorId;
    }

    public void setContributorId(BigInteger contributorId) {
        this.contributorId = contributorId;
    }

    public Integer getCycleNumber() {
        return cycleNumber;
    }

    public void setCycleNumber(Integer cycleNumber) {
        this.cycleNumber = cycleNumber;
    }

    public Integer getSegmentNumber() {
        return segmentNumber;
    }

    public void setSegmentNumber(Integer segmentNumber) {
        this.segmentNumber = segmentNumber;
    }

    public Integer getStageNumber() {
        return stageNumber;
    }

    public void setStageNumber(Integer stageNumber) {
        this.stageNumber = stageNumber;
    }

    public BigInteger getGroupId() {
        return groupId;
    }

    public void setGroupId(BigInteger groupId) {
        this.groupId = groupId;
    }

    public TournamentChallengeStatus getStatus() {
        return status;
    }

    public void setStatus(TournamentChallengeStatus status) {
        this.status = status;
    }

    public Instant getStartTime() {
        return startTime;
    }

    public void setStartTime(Instant startTime) {
        this.startTime = startTime;
    }

    public Instant getEndTime() {
        return endTime;
    }

    public void setEndTime(Instant endTime) {
        this.endTime = endTime;
    }

    public BigDecimal getBaseScore() {
        return baseScore;
    }

    public void setBaseScore(BigDecimal baseScore) {
        this.baseScore = baseScore;
    }

    public BigDecimal getFinalScore() {
        return finalScore;
    }

    public void setFinalScore(BigDecimal finalScore) {
        this.finalScore = finalScore;
    }

    public Map<String, Object> getExerciseDetails() {
        return exerciseDetails;
    }

    public void setExerciseDetails(Map<String, Object> exerciseDetails) {
        this.exerciseDetails = exerciseDetails;
    }
}
