package com.old.silence.content.domain.model;

import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import com.old.silence.content.domain.enums.tournament.TournamentParticipantStatus;
import com.old.silence.content.domain.enums.tournament.TournamentParticipantType;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdLogicalDeletionAuditable;
import com.old.silence.data.jdbc.core.converter.MapAttributeConverter;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.Instant;
import java.util.Map;

/**
 * 参赛记录表 - 赛事维度
 *
 * @author EX-GUOWEI869
 */
@Entity
public class TournamentParticipationRecord extends AbstractAutoGeneratedIdLogicalDeletionAuditable<BigInteger> {

    /**
     * 玩法ID
     */
    private BigInteger eventGameId;

    /**
     * 参赛单位ID
     */
    private BigInteger participantId;

    /**
     * 参赛单位类型
     */
    private TournamentParticipantType participantType;

    /**
     * 参赛状态
     */
    private TournamentParticipantStatus status;

    /**
     * 报名时间
     */
    private Instant registrationTime;

    /**
     * 总得分
     */
    private BigDecimal totalScore;

    /**
     * 扩展属性
     */
    @Convert(converter = MapAttributeConverter.class)
    private Map<String,Object> attributes;

    public BigInteger getEventGameId() {
        return eventGameId;
    }

    public void setEventGameId(BigInteger eventGameId) {
        this.eventGameId = eventGameId;
    }

    public BigInteger getParticipantId() {
        return participantId;
    }

    public void setParticipantId(BigInteger participantId) {
        this.participantId = participantId;
    }

    public TournamentParticipantType getParticipantType() {
        return participantType;
    }

    public void setParticipantType(TournamentParticipantType participantType) {
        this.participantType = participantType;
    }

    public TournamentParticipantStatus getStatus() {
        return status;
    }

    public void setStatus(TournamentParticipantStatus status) {
        this.status = status;
    }

    public Instant getRegistrationTime() {
        return registrationTime;
    }

    public void setRegistrationTime(Instant registrationTime) {
        this.registrationTime = registrationTime;
    }

    public BigDecimal getTotalScore() {
        return totalScore;
    }

    public void setTotalScore(BigDecimal totalScore) {
        this.totalScore = totalScore;
    }

    public Map<String, Object> getAttributes() {
        return attributes;
    }

    public void setAttributes(Map<String, Object> attributes) {
        this.attributes = attributes;
    }
}
